apiVersion: storage.gcp.crossplane.io/v1alpha3
kind: Bucket
metadata:
  name: backstage-dev-bucket-policy-testing-backstage-gcp
  labels:
    example: "true"
  annotations:
    # Note that this will be the actual bucket name so it has to be globally unique/available.
    crossplane.io/external-name: bucket-policy-testing-backstage
spec:
  location: US
  storageClass: MULTI_REGIONAL
  providerConfigRef:
    name: default
  deletionPolicy: Delete 
---
apiVersion: storage.gcp.crossplane.io/v1alpha1
kind: BucketPolicyMember
metadata:
  name: bucket-policy-testing-backstage
spec:
  forProvider:
    bucketRef:
      name: bucket-policy-testing-backstage
    # member: serviceAccount:<my-sa-email>
    serviceAccountMemberRef:
      name: perfect-test-sa
    role: roles/storage.objectAdmin
  providerConfigRef:
    name: gcp-provider    
---
apiVersion: storage.gcp.crossplane.io/v1alpha1
kind: BucketPolicy
metadata:
  name: bucket-policy-testing-backstage
spec:
  forProvider:
    bucketRef:
      name: bucket-policy-testing-backstage
    policy:
      bindings:
        - role: roles/storage.legacyBucketOwner
          members:
            - "projectEditor:<gcp-project>"
            - "projectOwner:<gcp-project>"
        - role: roles/storage.legacyBucketReader
          members:
            - "projectViewer:<gcp-project>"
        - role: roles/storage.objectAdmin
          serviceAccountMemberRefs:
            - name: perfect-test-sa
  providerConfigRef:
    name: gcp-provider
