apiVersion: storage.gcp.crossplane.io/v1alpha3
kind: Bucket
metadata:
  name: backstage-dev-asdfghjkl-gcp
  labels:
    example: "true"
  annotations:
    # Note that this will be the actual bucket name so it has to be globally unique/available.
    crossplane.io/external-name: asdfghjkl
spec:
  location: US
  storageClass: MULTI_REGIONAL
  providerConfigRef:
    name: default
  deletionPolicy: Delete    